services:
  auth-service:
    build: .
    image: inno-auth-service
    container_name: auth-service-app
    ports:
      - "${APP_PORT}:8080"
    volumes:
      - ./keys:/run/keys:ro
    environment:
      SERVER_PORT: 8080
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/${POSTGRES_DB}
      JWT_PRIVATE_KEY_LOCATION: file:/run/keys/private.pem
      JWT_PUBLIC_KEY_LOCATION: file:/run/keys/public.pem
      JWT_KEY_ID: ${JWT_KEY_ID:-auth-service-key}
      USER_SERVICE_URL: http://user-service:8080
    depends_on:
      auth-postgres:
        condition: service_healthy
    networks:
      - inno-net
      - auth-internal

  auth-postgres:
    image: postgres:16
    container_name: auth-service-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - auth-internal

volumes:
  postgres_data:

networks:
  inno-net:
    external: true
  auth-internal:
    driver: bridge